[package]
name = "rsdoom"
version = "0.1.0"
edition = "2024"
license="GPL-2.0-only"
default-run = "rsdoom"

[dependencies]
bytemuck = "1.25"
grid = "1.0"
itertools = "0.15"
log = { version = "0.4", features = ["release_max_level_warn", "max_level_debug", "kv", "kv_serde", "std"] }
rayon = "1.12"
sdl3 = { version = "0.20", features = ["static-link", "build-from-source", "raw-window-handle"] }
simple_logger = { version = "5.2", features = ["threads"] }
thiserror = "2.0"
truncate-integer = "0.5"
usize-conv = { version = "0.1", features = ["min-usize-64"] }
wgpu = "30.0"
winnow = "1.0"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[[bin]]
name = "rsdoom"

[lib]
name = "rsdoom"

[lints.clippy]
# UM, ACTUALLY
pedantic = { level = "deny", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "deny", priority = -1 }
# PERFORMANCE LINTS
perf = { level = "deny", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
